# Generated by Django 4.0.3 on 2022-03-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='media/bShop/Y%/m%/d%/', verbose_name='Изображение'),
        ),
    ]
