# Generated by Django 4.0.3 on 2022-04-04 17:31

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bShop', '0005_alter_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Подкатегория')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, default='media/bShop/temp/shablon.jpg', upload_to='media/bShop/%Y/%m/%d/', verbose_name='Изображение')),
                ('url', models.SlugField(max_length=1200, verbose_name='Ссылка')),
                ('category', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bShop.category')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='sub_category',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bShop.subcategory'),
        ),
    ]
