# Generated by Django 4.0.3 on 2022-04-04 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bShop', '0007_item_count_item_keyitem_item_price_item_skidka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Производитель')),
                ('contry', models.CharField(max_length=1000, verbose_name='Страна')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bShop.subcategory'),
        ),
        migrations.AddField(
            model_name='item',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bShop.model'),
        ),
    ]
