# Generated by Django 4.0.4 on 2022-05-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bShop', '0009_quizcategory_quizquestion_quiztype_quizresult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='name',
            field=models.CharField(choices=[(1, 'answer1'), (1, 'answer2'), (1, 'answer3'), (1, 'answer4'), (1, 'answer5'), (1, 'answer6'), (1, 'answer7'), (1, 'answer8'), (1, 'answer9'), (1, 'answer10'), (1, 'answer11'), (1, 'answer12'), (1, 'answer13'), (1, 'answer14'), (1, 'answer15'), (1, 'answer16'), (1, 'answer17'), (1, 'answer18'), (1, 'answer19'), (1, 'answer20'), (1, 'answer21'), (1, 'answer22'), (1, 'answer23'), (1, 'answer24'), (1, 'answer25'), (1, 'answer26')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quiztype',
            name='name',
            field=models.CharField(choices=[(1, 'oge'), (2, 'ege'), (3, 'diagnostic'), (4, 'create'), (5, None)], max_length=20),
        ),
    ]
