# Generated by Django 4.0.4 on 2022-05-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bShop', '0013_alter_quizquestion_name_alter_quiztype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='question_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='question_type',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
        migrations.DeleteModel(
            name='QuizType',
        ),
    ]
