# Generated by Django 4.0.4 on 2022-05-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bShop', '0015_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
