# Generated by Django 4.0.4 on 2022-05-09 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bShop', '0016_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='quiz',
            field=picklefield.fields.PickledObjectField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='answer',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='result',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='users',
            name='login',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
