# Generated by Django 4.0.4 on 2022-05-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bShop', '0017_quizresult_quiz_alter_quizresult_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='date_create',
            field=models.DateField(auto_now=True),
        ),
    ]
